image: maven:3.8-openjdk-11
stages:
  - build
  - test
java-build:
  stage: build
  script:
    - mvn clean compile
  only:
    - main
java-test:
  stage: test
  script:
    - mvn test
  only:
    - main
