spring:
  application:
    name: spring-multischema-router

  datasource:
    url: jdbc:postgresql://localhost:5432/multischemadb
    username: multischemauser
    password: multischemapass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    hibernate:
      ddl-auto: update
